[package]
name = "rust-blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
hex = "0.4.3"
sha2 = "0.10.9"
tokio = { version = "1", features = ["full"] }
tonic = "0.11"
prost = "0.12"
prost-types = "0.13.5"

[build-dependencies]
tonic-build = "0.11"
